/////////////////////////////////////////////////////////
//created by hmaya at 2015.10.11
//Draw curves for Functions
//{Li,i=0,1,2}
//L0 : x = asin(t),y= t,z = bsin(2t)
//L1 : x = asin(t+2¦Ð/3),y= t, z = bsin(2(t+2¦Ð/3)) 
//L2 : x = asin(t+4¦Ð/3),y= t, z = bsin(2(t+4¦Ð/3))
//t->[0,2]
//Parameters:
//proc drawFn(float $v_min,float $v_max,float $step,string $curveName)
//$v_min minimum value of x
//$v_max maximum value of x
//$step sample step
//$curveName
/////////////////////////////////////////////////////////

proc drawFn(float $v_min,float $v_max,float $step,string $curveName, int $ID){
    int $count_point = ($v_max - $v_min)/$step;
    //create curve
    curve -d 1 -p -2 1 0 -p 0 2 0 -p 1 1 0 -k 0 -k 1 -k 2 -n curve_temp;
    rebuildCurve -ch 1 -rpo 1 -rt 0 -end 1 -kr 2 -kcp 0 -kep 0 -kt 0 -s ($count_point-1) -d 1 -tol 0.01 "curve_temp";
    
    //define math function
    float $PI = 3.14159265;    
    float $a = 2.0;
    float $b = 2.0;
    float $factor = 2.0;
    float $t;
    int $n=0;
    for($t=$v_min;$t<=$v_max;$t=$t+$step){
        float $value_x[];
        float $value_y[];
        float $value_z[];
        if($ID == 0){        
              //L0 : x = asin(t),y= t,z = bsin(2t)
              $value_x[$n]= $a*sin($t);
              $value_y[$n]= $t;
              $value_z[$n]= $b*sin($factor*$t);
        }else if ($ID == 1){
              //L1 : x = asin(t+2¦Ð/3),y= t, z = bsin(2(t+2¦Ð/3)) 
              $value_x[$n]= $a*sin($t + 2*$PI/3);
              $value_y[$n]= $t;
              $value_z[$n]= $b*sin($factor*$t+ $factor*2*$PI/3);
        }else if ($ID == 2){
              //L2 : x = asin(t+4¦Ð/3),y= t, z = bsin(2(t+4¦Ð/3))
              $value_x[$n]= $a*sin($t + 4*$PI/3);
              $value_y[$n]= $t;
              $value_z[$n]= $b*sin($factor*$t + $factor*4*$PI/3);
            
        }
        
        move -a $value_x[$n] $value_y[$n] $value_z[$n] curve_temp.ep[$n];
        $n++;
    } //end for $t
    rename curve_temp $curveName;
}
//end proc

//Run Proc
drawFn(0.00001,30,0.1,"FnCurve0", 0);
drawFn(0.00001,30,0.1,"FnCurve1", 1);
drawFn(0.00001,30,0.1,"FnCurve2", 2);
